export const FETCH_PROJECT_LIST_SUCCESS = 'FETCH_PROJECT_LIST_SUCCESS'
export const FETCH_PROJECT_SINGLE_SUCCESS = 'FETCH_PROJECT_SINGLE_SUCCESS'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECT_SUCCESS'
export const FETCH_PROJECTS_ERROR = 'FETCH_PROJECT_ERROR'
export const FETCH_PROJECTS_START = 'FETCH_PROJECT_START'
//
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const RESET_PROJECT_CREATION = 'RESET_PROJECT_CREATION'
//
export const PROJECT_NEXT = 'PROJECT_NEXT'
export const FINISH_PROJECT = 'FINISH_PROJECT'
//
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
