// Get Project
export const FETCH_PROJECT_LIST_SUCCESS = 'FETCH_PROJECT_LIST_SUCCESS'
export const FETCH_PROJECT_SINGLE_SUCCESS = 'FETCH_PROJECT_SINGLE_SUCCESS'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECT_SUCCESS'
export const FETCH_PROJECTS_ERROR = 'FETCH_PROJECT_ERROR'
export const FETCH_PROJECTS_START = 'FETCH_PROJECT_START'
// Post Project
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const RESET_PROJECT_CREATION = 'RESET_PROJECT_CREATION'
//
export const PROJECT_NEXT = 'PROJECT_NEXT'
export const FINISH_PROJECT = 'FINISH_PROJECT'
// Post Catalog
export const CREATE_PROJECT_CATALOG = 'CREATE_PROJECT_CATALOG'
export const RESET_PROJECT_CREATION_CATALOG = 'RESET_PROJECT_CREATION_CATALOG'
// Get Catalog
export const FETCH_PROJECT_CATALOG_SUCCESS = "FETCH_PROJECT_CATALOG_SUCCESS"
export const FETCH_CATALOG_LIST_SUCCESS = "FETCH_CATALOG_LIST_SUCCESS"
export const FETCH_CATALOG_SINGLE_SUCCESS = "FETCH_CATALOG_SINGLE_SUCCESS"
// Get Navigation
export const GET_CATALOG_SUCCESS = "GET_CATALOG_SUCCESS"
export const GET_NAVIGATION_SUCCESS = "GET_NAVIGATION_SUCCESS"
// Post News
export const CREATE_NEWS = 'CREATE_NEWS'
export const RESET_NEWS = 'RESET_NEWS'
// Get News
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS'
export const FETCH_NEWS_NAVIGATOR = 'FETCH_NEWS_NAVIGATOR'
// Post Clients
export const CREATE_CLIENTS = 'CREATE_CLIENTS'
export const RESET_CLIENTS = 'RESET_CLIENTS'