export const FETCH_PROJECT_LIST_SUCCESS = 'FETCH_PROJECT_LIST_SUCCESS'
export const FETCH_PROJECT_SINGLE_SUCCESS = 'FETCH_PROJECT_SINGLE_SUCCESS'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECT_SUCCESS'
export const FETCH_PROJECTS_ERROR = 'FETCH_PROJECT_ERROR'
export const FETCH_PROJECTS_START = 'FETCH_PROJECT_START'
//
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const RESET_PROJECT_CREATION = 'RESET_PROJECT_CREATION'
//
export const PROJECT_NEXT = 'PROJECT_NEXT'
export const FINISH_PROJECT = 'FINISH_PROJECT'
//
export const CREATE_PROJECT_CATALOG = 'CREATE_PROJECT_CATALOG'
export const RESET_PROJECT_CREATION_CATALOG = 'RESET_PROJECT_CREATION_CATALOG'
//
export const FETCH_PROJECT_CATALOG_SUCCESS = "FETCH_PROJECT_CATALOG_SUCCESS"
export const FETCH_CATALOG_LIST_SUCCESS = "FETCH_CATALOG_LIST_SUCCESS"
export const FETCH_CATALOG_SINGLE_SUCCESS = "FETCH_CATALOG_SINGLE_SUCCESS"
//
export const GET_CATALOG_SUCCESS = "GET_CATALOG_SUCCESS"
export const GET_NAVIGATION_SUCCESS = "GET_NAVIGATION_SUCCESS"